allowBuilds:
  '@firebase/util': false
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  protobufjs: false
onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
